# Generated by Django 2.2.10 on 2020-03-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pagina_texto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagina',
            new_name='Inicio',
        ),
        migrations.RemoveField(
            model_name='patologia',
            name='imagen',
        ),
    ]
