# Generated by Django 2.2.11 on 2020-04-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200331_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, null=True)),
                ('texto', models.TextField(null=True)),
                ('logo', models.ImageField(upload_to='static/img')),
                ('tel', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inicio',
        ),
    ]
